### ISSUE TITLE
Can not get cargo to run after rustup update

### ISSUE THREAD

**Issue by hadysysdev** [emilk/eframe_template#112]
Following the **Testing locally** section of the READ-ME , i get the following error when i run the cargo command `cargo run --release`

`
error: the 'cargo.exe' binary, normally provided by the 'cargo' component, is not applicable to the '1.71.0-x86_64-pc-windows-msvc' toolchain
`

**Comment by hadysysdev** [comment]
removing the `rust-toolchain` file fixes the issue

**Comment by emilk** [comment]
rustup install 1.71.0 should fix it
