### ISSUE TITLE
The web app fails when the project is at `<username>.github.io`

### ISSUE THREAD

**Issue by Saphereye** [emilk/eframe_template#116]
**Problem**
The web app fails when the project is at `<username>.github.io`. This issue stems from this [workflow](https://github.com/emilk/eframe_template/blob/master/.github/workflows/pages.yml#L38). The current version will host the website on `<username>.github.io/<username>.github.io`, which is not ideal.

**Possible Solution**
The problem can be addressed by modifying the line to read as follows: `run: ./trunk build --release`. This resolution can be elucidated in the readme or documented as a comment.

**Comment by tomtuamnuq** [comment]
For me this problem arose after the upgrade of trunk from v0.18.8 to v.0.19.1. Before that gh-pages worked with the template, i.e. `run: ./trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"`. After the update references contained the name and repo multiple times, leading to 404 errors. 
Cause is likely the newly added finer control feature of trunk, see this [commit](https://github.com/trunk-rs/trunk/commit/391be74c74c320b3f01bf353d18bfc854d62bb85) from the release page of trunk for v0.19.0 regarding public, serve and websocket base.
I fixed the resolution issue by hardcoding the url completely, e.g.,
`run: ./trunk build --release --public-url https://tomtuamnuq.github.io/rusty-chaos-craftor/ `
@brunizzl  App persistence works for me with the hardcoded url

**Comment by Saphereye** [comment]
Can confirm the multiple occurrences of repo name in the URL that @tomtuamnuq faced. Adding to that, we can perhaps change the workflow to programmatically create the link.
```sh
echo "Repo owner: ${{ github.repository_owner }}"
echo "Repo name: ${{ github.event.repository.name }}"
REPO_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
echo "Repo URL: $REPO_URL"
./trunk build --release --public-url "$REPO_URL"
```

**Comment by sdasda7777** [comment]
I thought I was experiencing this issue, but the suggested fix above did not work for me, so I'm not so sure anymore 🤔

**Comment by trappitsch** [comment]
@sdasda7777: Looks like your workflow misses a `|` after `run` to define a multi-line command, see, e.g., [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun).

According to @Saphereye comment above, my whole `build` step in the `yaml` file now looks like this, which works great: 

```yml
- name: Build # build
  run: ./trunk build --release --public-url $public_url
    env:
      public_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
```

**Comment by sdasda7777** [comment]
There should be less indentation for `env` and `public_url`, but it does work now. Thank you so much! 😁

**Comment by trappitsch** [comment]
Thanks, you are absolutely right. copy-paste error :roll_eyes:
