### ISSUE TITLE
Documentation and examples for storage need to be updated to reflect recent changes.

### ISSUE THREAD

**Issue by jremb** [emilk/eframe_template#119]
Examples include snippets like
```rust
if let Some(storage) = cc.storage {
    if let Some(state) = eframe::get_value(storage, eframe::APP_KEY) {
        slf.state = state;
    }
}
```
There is no longer a `get_value` method here. In the documentation, it's suggested to use the `data` field of `egui::Memory`, but it's left completely opaque as to how.

**Comment by emilk** [comment]
`get_value` exists: https://docs.rs/eframe/latest/eframe/fn.get_value.html (if you compile with the `persistence ` feature enabled)

**Comment by trevorstr** [comment]
I had the same problem. This template repository doesn't say anything about having to add the `persistence` feature.
