### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by prokie** [emilk/eframe_template#133]
Hi.

I am trying to use this template and also set up custom DNS on the GitHub Page but I only get a blank page and this information in the Chrome developer console logs.

It works fine when I don't use `Custom DNS`.

```
Access to script at 'https://prokie.github.io/math_website/math_website-7f2c36504927be3b.js' from origin 'https://math.trennestam.se' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

How can I solve it?

**Comment by emilk** [comment]
I don't know - I think this is a question best asked somewhere else
