### ISSUE TITLE
Empty canvas during local testing

### ISSUE THREAD

**Issue by RockyXRQ** [emilk/eframe_template#141]
I'm currently using eframe-template with Rust Rover in win10 x86. At first time I did `cargo run` and everything seems just fine. But after I changed the code

```rust
        egui::TopBottomPanel::top("top_panel").show(ctx, |ui| {
            // The top panel is often a good place for a menu bar:

            egui::menu::bar(ui, |ui| {
                // NOTE: no File->Quit on web pages!
                let is_web = cfg!(target_arch = "wasm32");
                if !is_web {
                    ui.menu_button("File", |ui| {
                        if ui.button("Quit").clicked() {
                            ctx.send_viewport_cmd(egui::ViewportCommand::Close);
                        }
                    });
                    // ui.add_space(40.0); // from 16.0 to 40.0
                }
```

The canvas didn't show up, so I changed the value back (from 20.0 to 16.0), but seems the canvas still not show up. So I download the eframe-template and trying to run it without any change, I still get a empty canvas, I can't fix it with `cargo clean` and then rebuild.

![image](https://github.com/emilk/eframe_template/assets/34883463/e5d3e8c2-639a-453f-8b37-99ea3eb4e00c)

**Comment by RockyXRQ** [comment]
I got these

![image](https://github.com/emilk/eframe_template/assets/34883463/06340f58-f77b-4ddf-aee3-dd450e80c298)

**Comment by emilk** [comment]
You may wanna look into that `app.ron` and then try deleting it

**Comment by RockyXRQ** [comment]
OMG I deleted it and seems everything just alright now! Really appreciate! By the way can I know how this happened and what is the file `app.ron` for? Thanks again!

**Comment by c-git** [comment]
`app.ron` stores the state of the application so you can "resume". I haven't checked but based on what I've observed it serialized the state of the "App" Struct.
