### ISSUE TITLE
Ubuntu: native build failed to run with "libEGL warning: DRI2: failed to authenticate"

### ISSUE THREAD

**Issue by Mingun** [emilk/eframe_template#30]
I've created an example application using this template but native image failed to run with following error:
```console
$ cargo run --release
    Finished release [optimized] target(s) in 0.07s
     Running `/home/mingun/Projects/workspace/target/release/editor`
libEGL warning: DRI2: failed to authenticate
```
If anybody knows what the reason and how to fix it I appreciate. Web build (using supplied scripts) works fine.

Ubuntu 20.04.3 LTS

**Comment by emilk** [comment]
you may be missing graphics drivers. See https://github.com/emilk/egui/issues/380

Please open an issue in the egui repo instead, or add to the issue above
