### ISSUE TITLE
Cannot copy text from text edit singleline

### ISSUE THREAD

**Issue by Luis-Licea** [emilk/eframe_template#31]
I downloaded the template and compiled it. The app has a text-edit-singleline widget with some text. When compiled natively, I can select "Hello World!" and copy it using <kbd>Ctrl+C</kbd> , but when compiled for the web, I am able to select the text but not copy it in any way. 

Since copying the text was not working for the web, I tried to copy the text programmatically by doing the following:
```rust
// If the Copy button is clicked:
if ui.button("Copy").clicked() {
    // Clone the label text into the clipboard.
    ui.output().copied_text = label.clone();
}
```
Again, copying the code programmatically worked natively but not for the web. I tried this using Firefox in Android, and Firefox in Linux.
Any thoughts on why this is happening? I am writing a small app and I want to copy the text into the clipboard.

**Comment by emilk** [comment]
Does https://emilk.github.io/egui/ work?
Have you checked the debug console output in the browser?
Are you running the latest version for Firefox?
Have you tried any other browser?

**Comment by Luis-Licea** [comment]
> Does https://emilk.github.io/egui/ work?

Yes, the example works. The problem was with my setup.

I was using the VS Code "Live Server" extension instead of running `start_server.sh`.

**Comment by yangcancai** [comment]
The same with me , Ctrl+C not work for web. How to fix it? @Luis-Licea

**Comment by Luis-Licea** [comment]
Use the server provided by the repo, not a VSCode extension. For me it was `start_server.sh` but now I think it is by running `trunk server`.

**Comment by yangcancai** [comment]
> Use the server provided by the repo, not a VSCode extension. For me it was `start_server.sh` but now I think it is by running `trunk serve`.

For me the solution is #81
