### ISSUE TITLE
crash when resizing window (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION) 

### ISSUE THREAD

**Issue by gui2one** [emilk/eframe_template#63]
The default app crashes when resizing the window in both directions ( using the corner ). Resizing vertically only or horizontally only doesn't crash at all.
I am very new to Rust and Eframe/Egui. Is there a way to remedy this issue ?
I am on Win10.

**Comment by emilk** [comment]
Please make a detailed bug report in the `egui` repo!
