### ISSUE TITLE
cargo run --release error

### ISSUE THREAD

**Issue by wallace-dl** [emilk/eframe_template#90]
the  error is occur on  pull the  egui-template  and nothing to edit  ,how could i fix it ?

Compiling windows v0.42.0
   Compiling arboard v3.2.0
   Compiling darling v0.14.2
   Compiling enumset_derive v0.6.1
   Compiling kurbo v0.8.3
   Compiling enumset v1.0.12
   Compiling ron v0.8.0
   Compiling accesskit v0.8.1
   Compiling accesskit_consumer v0.10.0
   Compiling accesskit_windows v0.10.1
   Compiling accesskit_winit v0.7.1
   Compiling bytemuck v1.12.3
   Compiling ecolor v0.20.0
   Compiling emath v0.20.0
   Compiling epaint v0.20.0
   Compiling egui v0.20.0
   Compiling egui-winit v0.20.0
   Compiling egui_glow v0.20.0
   Compiling eframe v0.20.0
   Compiling eframe_template v0.1.0 (D:\java\workspace\rust\eframe_template-master)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 38s
     Running `target\debug\eframe_template.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\xxx\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\eframe-0.20.0\src\native\run.rs:399:25

![image](https://user-images.githubusercontent.com/16189493/208858855-32043d2c-7c74-4a89-bf24-37382aee9cf8.png)

**Comment by discite** [comment]
I am having the same error

**Comment by coderedart** [comment]
can you check if this is still happening with the latest master?

If you still get a crash, try running with `RUST_LOG=debug cargo run` and post the output.

**Comment by emilk** [comment]
You can also just try with eframe/egui 0.21 (just released)

**Comment by c-git** [comment]
Is this issue ongoing with the current version? I am not getting this issue.

**Comment by emilk** [comment]
this should be fixed
