### ISSUE TITLE
How do I remove a component?

### ISSUE THREAD

**Issue by caoyangyang1215** [emilk/eframe_template#98]
If I want to click the button to remove a component，how to do that？

I only found the visible attribute in the api

**Comment by bombless** [comment]
it's direct ui, so you don't need to set visibility, you just don't draw it.
e.g.

```rust
pub struct TemplateApp {
// ...

    hide: bool,
}
```
and
```rust
            if !self.hide && ui.button("Click to hide").clicked() {
                self.hide = true;
            }
```
