### ISSUE TITLE
mind your cache 

### ISSUE THREAD

**Issue by adsick** [emilk/eframe_template#99]
Hi, I'm trying to learn Leptos right now, but when I tried to run it's examples on a local machine I've seen just the leftovers from some eframe stuff I was doing before. When I refreshed the page that stuff was still there despite active Trunk with a Leptos app. Only force update helped (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>).

I'm not saying that there is anything wrong with this template, but I encountered some confusion so I decided to share it. Also I know that there is code in this repo that is responsible for making cache work, maybe it's not 100% correct? is it possible to only ship it in release builds?

Browser: Firefox 113.0.1

**Comment by coderedart** [comment]
I often get confused by this too. This is why there is a warning in the [README](https://github.com/emilk/eframe_template#web-locally) about caching behavior and how to get around this.

> assets/sw.js script will try to cache our app, and loads the cached version when it cannot connect to server allowing your app to work offline (like PWA). appending #dev to index.html will skip this caching, allowing us to load the latest builds during development.

**Comment by fdb** [comment]
Thanks for posting this. In my app it doesn't make sense to have a service worker so I just deleted that `<script>` in `index.html`.

**Comment by justinlovinger** [comment]
Note, the cache was disabled in <https://github.com/emilk/eframe_template/pull/102>, so this issue can be closed. In fact, the service-worker currently does nothing but throw harmless errors.
